# Generated by Django 5.1.4 on 2025-02-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('edad', models.DecimalField(decimal_places=0, max_digits=2)),
                ('matricula', models.CharField(max_length=11, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
